using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OverSurgery
{
    class DatabaseConnection
    {
        #region ATTRIBUTES 
        // Creates an instance of the DatabaseConnection class.
        private static DatabaseConnection _instance;

        // To ask Cristina: In the example this is private but can be accessed in Program.cs but can't here without being public. Why?
        private static string connectionStr;
        public static string ConnectionStr
        {
            set
            {
                connectionStr = value;
            }
        }


        // The SqlCconnection object used to store the connection to
        // the database.
        private SqlConnection connectionToDB;

        // The DataAdapter object used to open a table of the 
        // database.
        private SqlDataAdapter dataAdapter;

       
        #endregion

        #region METHODS

        public static DatabaseConnection getDatabaseConnectionInstance()
        {
            if (_instance == null)     
                _instance = new DatabaseConnection();
            
            return _instance;
        }

        /// <summary>
        /// Open the connection.
        /// </summary>
        public void openConnection()
        {
            // Create the connection to the database as an instance of 
            // System.Data.SqlClient.SqlConnection.
            connectionToDB = new SqlConnection(connectionStr);

            // Opens the connection
            connectionToDB.Open();
        }

        /// <summary>
        /// Get the data set generated by the SQL statement.
        /// </summary>
        /// <param name="SqlStatement"></param>
        /// <returns>Returns the data set.</returns>
        public DataSet getDataSet(string SqlStatement)
        {
            DataSet dataSet = new DataSet();

            // Opens connection.
            openConnection();

            // Create the object dataAdapter to manipulate a table from the
            // database SurgeryDatabase specified by connectionToDB.
            dataAdapter = new SqlDataAdapter(SqlStatement, connectionToDB);

            // Fills in the data set.
            dataAdapter.Fill(dataSet);

            // Closes the connection.
            closeConnection();

            // Return the dataset.
            return dataSet;
        }

        /// <summary>
        /// Close the connection.
        /// </summary>
        public void closeConnection()
        {
            // Closes the connection to the database.
            connectionToDB.Close();
        }
        #endregion

        #region CONSTRUCTORS
        #endregion
    }
}
